method: random
metric:
  name: val_acc
  goal: maximize
parameters:
  activation:    {values: [relu, silu, gelu, tanh, sigmoid]}
  optimizer:     {values: [sgd, nesterov-sgd, adam, adagrad, rmsprop, nadam]}
  batch_size:    {values: [64, 128, 256]}
  epochs:        {values: [20, 30]}
  lr:            {values: [0.01, 0.02, 0.05, 0.1]}
  momentum:      {values: [0.0, 0.9]}
  weight_decay:  {values: [0.0, 0.0005, 0.005]}
  seed:          {values: [1, 2, 3]}